interval = "5m"
db_path = "/home/myuser/.local/cache/soshi/soshi_db.json"
[syncthing]
    url = "http://localhost:8384"
    token = "<your-token>"
[ntfy]
    instance = "https://ntfy.sh"
    topic = "mytopic"
    token = "<your-token>"

